# Generated by Django 5.1.2 on 2024-10-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='nome_usuario',
        ),
        migrations.AlterField(
            model_name='worklog',
            name='time_spent',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
