# Generated by Django 5.1.2 on 2024-10-21 03:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_user_task_nome_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklog',
            name='date',
        ),
        migrations.RemoveField(
            model_name='worklog',
            name='time_spent',
        ),
        migrations.AddField(
            model_name='worklog',
            name='duration',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name='worklog',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worklog',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklogs', to='tasks.task'),
        ),
    ]
